export const HYDRATE_TRANSACTIONS = 'transactions/HYDRATE_TRANSACTIONS';

export const SEARCH_FOR_TRANSACTIONS = 'transactions/SEARCH_FOR_TRANSACTIONS';
export const RECORD_CONTACT_TRANSACTION =
  'transactions/RECORD_CONTACT_TRANSACTION';
export const TRANSACTION_FOUND = 'transactions/TRANSACTION_FOUND';
export const TRANSACTION_UPDATE = 'transactions/TRANSACTION_UPDATE';
export const TRANSACTIONS_STORAGE_KEY = 'transactions/TRANSACTIONS_STORAGE_KEY';

export const CANCEL_CONTACT_TRANSACTION_REQUESTING =
  'transactions/CANCEL_CONTACT_TRANSACTION_REQUESTING';
export const CANCEL_CONTACT_TRANSACTION_SUCCESS =
  'transactions/CANCEL_CONTACT_TRANSACTION_SUCCESS';
export const CANCEL_CONTACT_TRANSACTION_FAILURE =
  'transactions/CANCEL_CONTACT_TRANSACTION_FAILURE';
export const CONFIRM_CONTACT_TRANSACTION =
  'transactions/CONFIRM_CONTACT_TRANSACTION';
